@startuml
'https://plantuml.com/class-diagram

class Coordinate{
-longitude
-latitude
+Coordinate(double lon, double lat)
+GetLongitude()
+GetLatitude()
+isSouthernHemisphere()
+isNorthernHemisphere()

}

@enduml